### ISSUE TITLE
Probleme mit bytes und string

### ISSUE THREAD

**Issue by alxgross** [StefanHaring/E2Lox#1]
Hallo,

versuche meinen Miniserver zu kontaktieren und bin über Dein Programm gefallen. Habe es jetzt mal anprogrammiert als Test (aus Thonny heraus; Python 3.7) und bekomme aber das hier:

line 147, in _generate_session_key
    enc_session_key = cipher.encrypt(self._aes_key + b':' + self._aes_iv)
TypeError: can only concatenate str (not "bytes") to str

Worauf läuft bei dir das Programm?

**Comment by alxgross** [comment]
Hi, habe hier ein Demo-Prog geschrieben für Config 11.1 https://github.com/alxgross/Loxone_Websockets_Demo

**Comment by StefanHaring** [comment]
> 
> 
> Hallo,
> 
> versuche meinen Miniserver zu kontaktieren und bin über Dein Programm gefallen. Habe es jetzt mal anprogrammiert als Test (aus Thonny heraus; Python 3.7) und bekomme aber das hier:
> 
> line 147, in _generate_session_key
> enc_session_key = cipher.encrypt(self._aes_key + b':' + self._aes_iv)
> TypeError: can only concatenate str (not "bytes") to str
> 
> Worauf läuft bei dir das Programm?

Hi, 

Es handelt sich um ein Dreambox Plugin. OE2.5 (Dreambox OS) verwendet Python 2.7.

Unter Python 2.7 kann man Bytes und Strings direkt zusammenhängen. Unter Python 3 wird zwischen den 2 Typen differenziert, daher geht das nicht und das Script müsste angepasst werden.

Gruß
